services:
  - type: web
    name: zenzone
    env: node
    plan: free
    buildCommand: |
      npm ci
      npm ci --prefix client --include=dev
      npm run build --prefix client
      npm ci --prefix server
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 5000
      # Add these in the Render dashboard with secure values
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
    startCommand: node server/server.js
    autoDeploy: true
